// Code generated by "stringer -type ErrorClass -trimprefix ErrorClass -tags static"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorClassNone-0]
	_ = x[ErrorClassNoMemory-1]
	_ = x[ErrorClassOS-2]
	_ = x[ErrorClassInvalid-3]
	_ = x[ErrorClassReference-4]
	_ = x[ErrorClassZlib-5]
	_ = x[ErrorClassRepository-6]
	_ = x[ErrorClassConfig-7]
	_ = x[ErrorClassRegex-8]
	_ = x[ErrorClassOdb-9]
	_ = x[ErrorClassIndex-10]
	_ = x[ErrorClassObject-11]
	_ = x[ErrorClassNet-12]
	_ = x[ErrorClassTag-13]
	_ = x[ErrorClassTree-14]
	_ = x[ErrorClassIndexer-15]
	_ = x[ErrorClassSSL-16]
	_ = x[ErrorClassSubmodule-17]
	_ = x[ErrorClassThread-18]
	_ = x[ErrorClassStash-19]
	_ = x[ErrorClassCheckout-20]
	_ = x[ErrorClassFetchHead-21]
	_ = x[ErrorClassMerge-22]
	_ = x[ErrorClassSSH-23]
	_ = x[ErrorClassFilter-24]
	_ = x[ErrorClassRevert-25]
	_ = x[ErrorClassCallback-26]
	_ = x[ErrorClassCherrypick-27]
	_ = x[ErrorClassDescribe-28]
	_ = x[ErrorClassRebase-29]
	_ = x[ErrorClassFilesystem-30]
	_ = x[ErrorClassPatch-31]
	_ = x[ErrorClassWorktree-32]
	_ = x[ErrorClassSHA-33]
	_ = x[ErrorClassHTTP-34]
	_ = x[ErrorClassInternal-35]
	_ = x[ErrorClassGrafts-36]
}

const _ErrorClass_name = "NoneNoMemoryOSInvalidReferenceZlibRepositoryConfigRegexOdbIndexObjectNetTagTreeIndexerSSLSubmoduleThreadStashCheckoutFetchHeadMergeSSHFilterRevertCallbackCherrypickDescribeRebaseFilesystemPatchWorktreeSHAHTTPInternalGrafts"

var _ErrorClass_index = [...]uint8{0, 4, 12, 14, 21, 30, 34, 44, 50, 55, 58, 63, 69, 72, 75, 79, 86, 89, 98, 104, 109, 117, 126, 131, 134, 140, 146, 154, 164, 172, 178, 188, 193, 201, 204, 208, 216, 222}

func (i ErrorClass) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorClass_index)-1 {
		return "ErrorClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorClass_name[_ErrorClass_index[idx]:_ErrorClass_index[idx+1]]
}
