name: git2go CI
on:
  pull_request:
  push:
    branches:
    - main
    - release-*
    - v*

jobs:

  build-static:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.25', '1.26' ]
    name: Go ${{ matrix.go }} (bundled static)

    runs-on: ubuntu-24.04

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        make build-libgit2-static
    - name: Test
      run: make TEST_ARGS=-test.v test-static

  build-dynamic:
    strategy:
      fail-fast: false
    name: Go (bundled dynamic)

    runs-on: ubuntu-24.04

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
      id: go
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        make build-libgit2-dynamic
    - name: Test
      run: make TEST_ARGS=-test.v test-dynamic

  build-system-dynamic:
    strategy:
      fail-fast: false
      matrix:
        libgit2:
          - 'v1.9.6'
    name: Go (system-wide, dynamic)

    runs-on: ubuntu-24.04

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
      id: go
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build libgit2 ${{ matrix.libgit2 }}
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        sudo env BUILD_LIBGIT_REF=${{ matrix.libgit2 }} ./script/build-libgit2.sh --dynamic --system
        sudo ldconfig
    - name: Test
      run: make TEST_ARGS=-test.v test

  build-system-static:
    strategy:
      fail-fast: false
    name: Go (system-wide, static)

    runs-on: ubuntu-24.04

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
      id: go
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build libgit2
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        sudo env BUILD_LIBGIT_REF=v1.9.6 ./script/build-libgit2.sh --static --system
        sudo ldconfig
    - name: Test
      run: go test --count=1 --tags "static,system_libgit2" ./...

  race:
    name: Go (race)
    runs-on: ubuntu-24.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
      id: go
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        make build-libgit2-static
    - name: Test
      run: go test --tags "static" --race --count=1 -skip '^(TestCertificateCheck|TestRemoteConnect|TestRemoteConnectOption|TestRemoteLs|TestRemoteLsFiltering|TestRemoteCredentialsCalled|TestCloneWithHTTPUrl|TestRemoteSSH)$' ./...

  check-generate:
    name: Check generated files were not modified
    runs-on: ubuntu-24.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
      id: go
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install libgit2 build dependencies
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        go install golang.org/x/tools/cmd/stringer@v0.48.0
    - name: Generate files
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        make generate
    - name: Check nothing changed
      run: git diff --quiet --exit-code || (echo "detected changes after generate" ; git status ; exit 1)
